# Generated by Django 4.1 on 2022-08-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
